# Generated by Django 4.2.5 on 2023-09-17 06:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_diagnosticreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='report_file',
            field=models.FileField(upload_to=users.models.user_report_upload_path),
        ),
    ]
