# Generated by Django 4.2.5 on 2023-09-28 06:02

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_report_upload_path),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='family_medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='gynological_disorder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='immunization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='lifestyle_factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='mental_health_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='past_hospitalization',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='social_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='surgical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
