# Generated by Django 4.2.5 on 2023-09-16 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField()),
                ('family_medical_history', models.TextField()),
                ('medication', models.TextField()),
                ('immunization', models.TextField()),
                ('lifestyle_factor', models.TextField()),
                ('allergies', models.TextField()),
                ('past_hospitalization', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('surgical_history', models.TextField()),
                ('social_history', models.TextField()),
                ('mental_health_history', models.TextField()),
                ('gynological_disorder', models.TextField()),
                ('additional_information', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
