"""
Django settings for medgpt project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.contrib import staticfiles

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'shbyj%j#6#z@br!u((5@v!2tc1--yf78jr^60q(3l^omymxml+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',  # Add this line
    'chat',
    'profiles',  # Add this line
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medgpt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medgpt.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'medgpt',  # Replace with your database name
        'USER': 'medgpt',  # Replace with your database user
        'PASSWORD': 'Stark123',  # Replace with your database password
        'HOST': 'localhost',  # Set the database host (e.g., 'localhost' for a local MySQL server)
        'PORT': '3306',  # Set the port for MySQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'  # Add this line
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "staticfiles"
STATICFILES_DIRS = ["static"]

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = 'success'

MEDIA_URL = "/media/"
MEDIA_ROOT = "media"

# Allow file uploads
FILE_UPLOAD_PERMISSIONS = 0o644  # Permissions for uploaded files (readable by anyone)

# File upload size limit (adjust as needed)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB (increased limit)

# Enable the messages framework
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Use the default storage backend for uploaded files
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtppro.zoho.in'  # Replace with your SMTP server's hostname
EMAIL_PORT = 465  # Replace with your SMTP server's port (587 for TLS, 465 for SSL)
EMAIL_USE_TLS = False  # Use TLS (True or False)
EMAIL_USE_SSL = True  # Use SSL (True or False)
EMAIL_HOST_USER = 'docuassit@xitegroup.online'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'Stark@12'  # Replace with your email password
EMAIL_FROM = 'docuassit@xitegroup.online'  # Replace with your email address


# Define the session engine (default is database-backed sessions)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Define the session serializer (use the JSON serializer)
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Set the session cookie name (optional, but recommended)
SESSION_COOKIE_NAME = 'my_session_cookie_name'

# Set the session cookie age (optional)
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# Set the session cookie domain (optional)
SESSION_COOKIE_DOMAIN = None  # Use the current domain

# Set the session cookie path (optional)
SESSION_COOKIE_PATH = '/'  # Use the root path

# Enable session security features (optional)
SESSION_COOKIE_SECURE = False  # Set to True for HTTPS only
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Or 'Strict' for stricter security

# Enable automatic session expiration (optional)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # False by default

